version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    depends_on: 
      - db
    ports: 
      - "443:443"
  db:
    build: ./db
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: kiwi_basket
    ports: 
      - "3306:3306"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
